#!/usr/bin/env python3
"""
Generate lookup table for GPIO to RGB555 conversion.

Pin mapping (GP29-44 capture):
  Bit 0: GP29 (PCLK) - ignored
  Bit 1: GP30 (unused)
  Bit 2: GP31 (G3), Bit 3: GP32 (G4), Bit 4: GP33 (G1), Bit 5: GP34 (G2)
  Bit 6: GP35 (B0), Bit 7: GP36 (G0), Bit 8: GP37 (B2), Bit 9: GP38 (B1)
  Bit 10: GP39 (B4), Bit 11: GP40 (B3), Bit 12: GP41 (R1), Bit 13: GP42 (R0)
  Bit 14: GP43 (R3), Bit 15: GP44 (R2)
"""

def gpio_to_rgb555(gpio_data):
    """Convert 16-bit GPIO data to RGB555 based on actual pin mapping."""

    # Extract Blue bits (B0-B4)
    b0 = (gpio_data >> 6) & 1   # GP35
    b1 = (gpio_data >> 9) & 1   # GP38
    b2 = (gpio_data >> 8) & 1   # GP37
    b3 = (gpio_data >> 11) & 1  # GP40
    b4 = (gpio_data >> 10) & 1  # GP39
    b = (b0 << 0) | (b1 << 1) | (b2 << 2) | (b3 << 3) | (b4 << 4)

    # Extract Green bits (G0-G4)
    g0 = (gpio_data >> 7) & 1   # GP36
    g1 = (gpio_data >> 4) & 1   # GP33
    g2 = (gpio_data >> 5) & 1   # GP34
    g3 = (gpio_data >> 2) & 1   # GP31
    g4 = (gpio_data >> 3) & 1   # GP32
    g = (g0 << 0) | (g1 << 1) | (g2 << 2) | (g3 << 3) | (g4 << 4)

    # Extract Red bits (R0-R3, R4=0 since GP45 not captured)
    r0 = (gpio_data >> 13) & 1  # GP42
    r1 = (gpio_data >> 12) & 1  # GP41
    r2 = (gpio_data >> 15) & 1  # GP44
    r3 = (gpio_data >> 14) & 1  # GP43
    r = (r0 << 0) | (r1 << 1) | (r2 << 2) | (r3 << 3)  # R4 = 0

    # Combine into RGB555: RRRRR GGGGG BBBBB
    return (r << 10) | (g << 5) | b

def generate_lut():
    """Generate complete 64K lookup table."""
    print("Generating 64K GPIO->RGB555 lookup table...")
    lut = []
    for i in range(65536):
        rgb555 = gpio_to_rgb555(i)
        lut.append(rgb555)
        if (i + 1) % 8192 == 0:
            print(f"  {i+1}/65536 entries...")
    return lut

def write_c_header(lut, filename):
    """Write LUT as C header file."""
    print(f"Writing to {filename}...")

    with open(filename, 'w') as f:
        f.write("/**\n")
        f.write(" * Auto-generated GPIO to RGB555 lookup table\n")
        f.write(" * \n")
        f.write(" * Maps 16-bit GPIO data (GP29-44) to RGB555 based on MVS pin mapping.\n")
        f.write(" * Size: 65536 entries × 2 bytes = 128 KB\n")
        f.write(" * \n")
        f.write(" * Generated by scripts/generate_gpio_lut.py\n")
        f.write(" */\n\n")
        f.write("#ifndef GPIO_RGB_LUT_H\n")
        f.write("#define GPIO_RGB_LUT_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("// Lookup table: gpio_to_rgb555_lut[gpio_data] = rgb555\n")
        f.write("static const uint16_t gpio_to_rgb555_lut[65536] = {\n")

        # Write 8 entries per line for readability
        for i in range(0, 65536, 8):
            entries = [f"0x{lut[j]:04x}" for j in range(i, min(i + 8, 65536))]
            line = "    " + ", ".join(entries)
            if i + 8 < 65536:
                line += ","
            f.write(line + "\n")

        f.write("};\n\n")
        f.write("#endif // GPIO_RGB_LUT_H\n")

    print(f"Done! LUT written to {filename}")

if __name__ == "__main__":
    import os
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)
    output_path = os.path.join(project_dir, "src", "video", "gpio_rgb_lut.h")

    lut = generate_lut()
    write_c_header(lut, output_path)

    # Verify a few test cases
    print("\nVerifying test cases:")
    print(f"  0x0000 -> 0x{gpio_to_rgb555(0x0000):04x} (all zeros)")
    print(f"  0xFFFF -> 0x{gpio_to_rgb555(0xFFFF):04x} (all ones)")
    print(f"  LUT[0x0000] = 0x{lut[0x0000]:04x}")
    print(f"  LUT[0xFFFF] = 0x{lut[0xFFFF]:04x}")
